DESCRIBE DEPARTMENTS; 

SELECT * FROM USER_TABLES;

DESCRIBE EMP_10
CREATE TABLE EMP_10(C1 NUMBER(10), C2 VARCHAR(10));
CREATE TABLE 100-EMP(C1 NUMBER(10), C2 VARCHAR(10));
CREATE TABLE EMP-100(C1 NUMBER(10), C2 VARCHAR(10));
CREATE TABLE 100_EMP(C1 NUMBER(10), C2 VARCHAR(10));

SELECT * FROM EMP_10; 

INSERT INTO EMP_10(C1,C2) VALUES (1,'A');
INSERT INTO EMP_10(C1,C2) VALUES (1,'A');
SELECT * FROM EMP_10;
UPDATE EMP_10 SET C2='B' WHERE C1 = 1;
DELETE FROM EMP_10;

SELECT * FROM DEPARTMENTS;

INSERT INTO DEPARTMENTS
(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) 
VALUES(999, 'IT', NULL, 1700);

COMMIT;

SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = '50'
GROUP BY JOB_ID
ORDER BY AVG(SALARY) DESC;

SELECT * FROM employees;

SELECT FIRST_NAME||' '||LAST_NAME AS NAME, SALARY * 12 AS ANNUAL_INCOME
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT FIRST_NAME || 
       LAST_NAME || 
       JOB_ID
FROM EMPLOYEES;

SELECT FIRST_NAME || ''||
      LAST_NAME||
      '('||JOB_ID||')'
FROM EMPLOYEES;

SELECT FIRST_NAME||LAST_NAME || '의 연봉은 ' || SALARY*12 || '입니다' AS TEXT
FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE LAST_NAME = 'King';

SELECT FIRST_NAME||' '||LAST_NAME AS NAME ,
       SALARY,
       COMMISSION_PCT,
       (COMMISSION_PCT * SALARY) 
FROM EMPLOYEES
ORDER BY SALARY DESC;

/*null값 배우는 중*/
/*오라클은 기본적으로 중복된 행을 모두 display*/
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
ORDER BY DEPARTMENT_NAME;

/*DISTINCT로 중복제거*/
SELECT DISTINCT DEPARTMENT_NAME
FROM DEPARTMENTS
ORDER BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, MANAGER_ID
FROM DEPARTMENTS;

DESCRIBE EMPLOYEES;
DESCRIBE DEPARTMENTS;
--실습
SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, 
       FIRST_NAME||' '||LAST_NAME AS NAME ,
       EMAIL
FROM EMPLOYEES;

DESCRIBE DEPARTMENTS;

SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

DESCRIBE EMPLOYEES;

SELECT EMPLOYEE_ID || ', ' || 
       FIRST_NAME || ', ' ||
       LAST_NAME || ', ' ||
       EMAIL || ', ' ||
       PHONE_NUMBER || ', ' ||
       HIRE_DATE || ', ' ||
       JOB_ID || ', ' ||
       SALARY || ', ' ||
       COMMISSION_PCT || ', ' ||
       MANAGER_ID || ', ' ||
       DEPARTMENT_ID AS "THE OUTPUT"
FROM EMPLOYEES;

--WHERE

SELECT LAST_NAME, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90 AND SALARY <= 20000;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 90 OR SALARY <= 20000;

--between
SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 10000 AND 20000;

SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS
WHERE LOCATION_ID IN ('1500', '1700');

--LIKE SQL
SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'M%';

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '__ng';

SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'K%ng';

--is null
SELECT LAST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID = NULL; --NULL은 =으로 검색불가

SELECT LAST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

SELECT LAST_NAME
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

SELECT LAST_NAME
FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT LAST_NAME
FROM EMPLOYEES
WHERE COMMISSION_PCT >= 0;

--정렬 : alias로도 정렬가능
SELECT LAST_NAME AS ENAME, DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY ENAME;

-- COLUMN 정해서 정렬시키기 --권장하는 방식은 아니다. 
SELECT LAST_NAME, SALARY*12 
FROM EMPLOYEES
ORDER BY 2 DESC;

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
ORDER BY LAST_NAME DESC, SALARY DESC;


--실습2
DESC DEPARTMENTS;
DESC EMPLOYEES;

SELECT first_name, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE MANAGER_ID = 100 AND (SALARY BETWEEN 10500 AND 17000)
ORDER BY SALARY DESC;

SELECT first_name, DEPARTMENT_ID, SALARY
FROM EMPLOYEES
WHERE MANAGER_ID = 100 AND (SALARY > 10500 AND SALARY <= 17000)
ORDER BY SALARY DESC;

-----------------------------------------------------------
SELECT LAST_NAME || ' ' || FIRST_NAME AS NAME, department_id
FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 20 OR department_id = 30 OR DEPARTMENT_ID = 40)
AND (FIRST_NAME LIKE 'S%');

--sample answer
SELECT * FROM EMPLOYEES
        WHERE DEPARTMENT_ID IN (20,30,40)
        AND FIRST_NAME LIKE 'S%';
SELECT * FROM EMPLOYEES
        WHERE DEPARTMENT_ID IN (20,30,40)
        AND FIRST_NAME >= 'S'
        AND FIRST_NAME < 'T';
--------------------------------
-----------------------------------

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '__a%';

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%MAN';

SELECT FIRST_NAME || ' ' || LAST_NAME || ', ' || '(' || EMAIL || '@hyundai-autoever.com) : ' || NVL(COMMISSION_PCT, 0) || ', ' || DECODE(MANAGER_ID, NULL, '사장') AS OUTPUT
FROM EMPLOYEES





